// <auto-generated />
using System;
using EFcoreOneToOneBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFcoreOneToOneBug.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211029115239_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFcoreOneToOneBug.A", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("A");
                });

            modelBuilder.Entity("EFcoreOneToOneBug.B", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AId")
                        .IsUnique();

                    b.ToTable("B");
                });

            modelBuilder.Entity("EFcoreOneToOneBug.B", b =>
                {
                    b.HasOne("EFcoreOneToOneBug.A", "A")
                        .WithOne("B")
                        .HasForeignKey("EFcoreOneToOneBug.B", "AId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A");
                });

            modelBuilder.Entity("EFcoreOneToOneBug.A", b =>
                {
                    b.Navigation("B");
                });
#pragma warning restore 612, 618
        }
    }
}
